### ISSUE TITLE
Failed to start cluster service when calling `run-functional-tests -n 2`

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#1368] opened 2024-03-25 07:09 UTC
```
server2:/opt/crmsh # ./test/run-functional-tests -n 2
INFO: Loading docker image nyang23/haleap:15.5...
INFO: Create ha specific docker network "ha_network_first"...
INFO: Create ha specific docker network "ha_network_second"...
INFO: Deploying "hanode1"...
INFO: Deploying "hanode2"...
                            Successfully copied 172MB to hanode2:/opt/crmsh
INFO: Building crmsh on "hanode2"...
                            Successfully copied 172MB to hanode1:/opt/crmsh
INFO: Building crmsh on "hanode1"...
INFO: Create user 'alice' on hanode2
INFO: Create user 'alice' on hanode1
INFO: Create user 'bob' on hanode2
INFO: Create user 'bob' on hanode1
INFO: Create user 'carol' on hanode2
INFO: Create user 'carol' on hanode1
INFO: Copy corosync.conf to hanode1 hanode2
ERROR: Failed to start cluster service on "hanode1"
server2:/opt/crmsh # !docker
docker exec -it hanode1 bash
hanode1:/ # crm cluster start
ERROR: 'hanode1'
Traceback (most recent call last):
  File "/usr/sbin/crm", line 53, in <module>
    rc = main.run()
  File "/usr/lib/python3.6/site-packages/crmsh/main.py", line 370, in run
    upgradeutil.upgrade_if_needed()
  File "/usr/lib/python3.6/site-packages/crmsh/upgradeutil.py", line 162, in upgrade_if_needed
    _upgrade(nodes, seq)
  File "/usr/lib/python3.6/site-packages/crmsh/upgradeutil.py", line 138, in _upgrade
    crmsh.healthcheck.feature_fix(feature, nodes, ask)
  File "/usr/lib/python3.6/site-packages/crmsh/healthcheck.py", line 101, in feature_fix
    return feature.fix_cluster(nodes, ask)
  File "/usr/lib/python3.6/site-packages/crmsh/healthcheck.py", line 148, in fix_cluster
    remote_nodes.remove(local_node)
KeyError: 'hanode1'
```

**Comment by liangxin1300** [comment] 2024-03-25 07:11
Fixed in #1369

**Comment by nicholasyang2022** [comment] 2024-04-01 07:20
_Reopen as #1369 has not got merged._

This problem seems to be caused by changes in #1312, which makes `list_cluster_nodes` to return IP addresses if cib does not exist.

We should reconsider whether that change is valid, as it breaks a widely used interface, and moreover, `crm cluster start --all` does not work anymore with latest crmsh-4.6 in a cluster setup with yast2-cluster.

**Comment by liangxin1300** [comment] 2024-04-01 13:25
Yes, #1368 is the regression issue introduced by #1312.
While #1312 was for this issue:
```
# no cib, but has IP list in corosync.conf
# crm cluster start --all
ERROR: cluster.start: Cannot get the node list from cluster
```

@zzhou1 What do you think?

**Comment by zzhou1** [comment] 2024-04-02 03:45
@nicholasyang2022
> `crm cluster start --all` does not work anymore with latest crmsh-4.6 in a cluster setup with yast2-cluster.

This should be fixed if so. Any further details about the failure situation? 

I'm a little confused here. Since the code of #1312 is in SLE product. From the quick check, I didn't run into the likely problem you mentioned here. Where my system has corosync running, but pacemaker is down.  

> While #1312 was for this issue:
> 
> ```
> # no cib, but has IP list in corosync.conf
> # crm cluster start --all
> ERROR: cluster.start: Cannot get the node list from cluster
> ```

The design of the fix sounds reasonable to me.

Well, I'm lagging behind on the detailed failure code.

**Comment by nicholasyang2022** [comment] 2024-04-02 03:59
> crm cluster start --all does not work anymore with latest crmsh-4.6 in a cluster setup with yast2-cluster.
>
> This should be fixed if so. Any further details about the failure situation?
>
> I'm a little confused here. Since the code of #1312 is in SLE product. From the quick check, I didn't run into the likely problem you mentioned here. Where my system has corosync running, but pacemaker is down.

Yeah it should be fixed. But the implementation in #1312 changes what
`list_cluster_nodes` returns, which is widely used in crmsh and many
of those callers may expect receiving a hostname and use it in ssh. If
IP addresses are returned, they will not work properly.

Just take #1312 itself as an example. It uses the returned IP
addresses with `ClusterShell` and does not work in latest crmsh-4.6 as
`ClusterShell` requires the target node has passwordless ssh
authentication setup.

Instead of changing what `list_cluster_nodes` returns, it is better to
add a new function to retrieve node IP addresses for corosync and use
it only when the caller is ready to handle IP addresses.

**Comment by liangxin1300** [comment] 2024-04-02 05:49
Got you, I will make the change

**Comment by liangxin1300** [comment] 2024-04-03 01:33
New PR in #1377

**Closed** 2024-04-03 03:07 UTC
